name: CI
on: push
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: yarn
    - run: yarn lint
    - run: yarn cucumber --order random --retry 2 --retry-tag-filter "flakey"
